package com.PLCompanyAccountingBackend.repository;

import com.PLCompanyAccountingBackend.models.ResearchDevelopmentActivitiesCostsEvent;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ResearchDevelopmentActivitiesCostsEventRepository extends JpaRepository<ResearchDevelopmentActivitiesCostsEvent, Long> {
}
